import React from 'react';
import VideoCards from "../../components/video_cards/VideoCards";
import {HomePageContainer, HomePageContentContainer} from "./HomePageStyles";
import NavigationDrawer from "../../components/navigation_drawer/NavigationDrawer";
import NavigationAppBar from "../../components/appbar/NavigationAppBar";


function HomePage(props) {
    return (
        <>
        <NavigationAppBar/>
        <HomePageContainer>
                <NavigationDrawer/>
                <HomePageContentContainer>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>
                        <VideoCards
                            thumbnail='https://i.ytimg.com/an_webp/9zBsdzdE4sM/mqdefault_6s.webp?du=3000&sqp=CJHYo6oG&rs=AOn4CLBkh0cI461koHfri67zc2Jd92cR8A'
                            channelImg='https://yt3.ggpht.com/ewC1nleORkp8FkJpZrDPrqmVry6JHkUV_1eWuYFLlXTJGaoQ0v0qn1YLdZcpffMaRJrMMYIT5_U=s68-c-k-c0x00ffffff-no-rj'
                        >
                        </VideoCards>

                </HomePageContentContainer>
        </HomePageContainer>
        </>
    );
}

export default HomePage;